pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker run -v $PWD/Core_DOM:/Core_DOM logicalhacking:isabelle2019 isabelle build -D /Core_DOM'
            }
        }
    }
}
